### PR TITLE
Add a new '/' delimiter

### PR DESCRIPTION
**Pull request by reemaparakh**
# Description

This PR adds a new delimiter `/`.

## Steps to Test or Reproduce
Input
```
/ Copyright 2006, Google Inc.
/ All rights reserved.
/
/ Redistribution and use in source and binary forms, with or without
/ modification, are permitted provided that the following conditions are
/ met:
/
/     * Redistributions of source code must retain the above copyright
/ notice, this list of conditions and the following disclaimer.
/     * Redistributions in binary form must reproduce the above
/ copyright notice, this list of conditions and the following disclaimer
/ in the documentation and/or other materials provided with the
/ distribution.
```
Output
```
Copyright 2006, Google Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.
```

### CODE REVIEW

**Comment by mynameistechno** [comment]
@reemaparakh can you fix the one test? We need to increment the # of tests in the assertion.

**Comment by reemaparakh** [comment]
@mynameistechno Fix the test. Please review. Thanks!

**Comment by mynameistechno** [comment]
> @mynameistechno Fix the test. Please review. Thanks!

I don't see the change. The test is still failing. Thanks

**Comment by reemaparakh** [comment]
@mynameistechno Fix the test. Please review. Thanks!

**Pull request merged**
